controllers/AdminController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\User;

use app\models\Article;
use app\models\News;
use app\models\Clinic;
use app\models\Department;
use app\models\Doctor;
use app\models\Visit;
use app\models\Preferences;


class AdminController extends Controller
{

    public function beforeAction($action) {
        $this->enableCsrfValidation = false;

        /*if (\Yii::$app->user->isGuest) {
            return $this->redirect('login', 302);
        }*/

        return parent::beforeAction($action);
    }


    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => [
                            'logout',
                            'home',
                            'add-article',
                            'add-clinic',
                            'add-department',
                            'add-news',
                            'add-doctor',
                            'add-client',
                            'add-banner',
                            'add-gallery',
                            'edit-preferences',
                            'all-articles',
                            'all-clinics',
                            'all-departments',
                            'all-news',
                            'all-doctors',
                            'all-clients',
                            'all-banners',
                            'all-gallery',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->redirect('home', 302);
        }


        if(isset($_POST['User'])) {
            $username = $_POST['User']['username'];
            $password = $_POST['User']['password'];

            if ($username == 'admin' && $password == 'DPeMDhg9GF34zMJC') {
                $user = User::findByUsername($username);
                $res = Yii::$app->user->login($user, 3600*24*30);

                if ($res == true) {
                    return $this->redirect('home', 302);
                }
            }
        }

        $this->layout = 'empty';
        return $this->render('login');
    }


    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect('login', 302);
    }


    public function actionHome()
    {
        // DeviceController::sendPushNotifications("Test Notification");

        $articles_count = Article::find()->count();
        $news_count = News::find()->count();
        $clinics_count = Clinic::find()->count();
        $departments_count = Department::find()->count();
        $doctors_count = Doctor::find()->count();
        $visits_count = Visit::find()->count();

        $clients_count = count(glob("../../clients/*.{jpg,png,gif}", GLOB_BRACE));
        $banners_count = count(glob("../../banners/*.{jpg,png,gif}", GLOB_BRACE));
        
        return $this->render('Home', [
            'articles_count' => $articles_count,
            'news_count' => $news_count,
            'clinics_count' => $clinics_count,
            'departments_count' => $departments_count,
            'doctors_count' => $doctors_count,
            'visits_count' => $visits_count,
            'clients_count' => $clients_count,
            'banners_count' => $banners_count,
        ]);
    }


    public function actionAddArticle()
    {
        $is_insert = false;
        $insert_success = false;
        $message = "";

        if (isset($_POST['Article']))
        {
            $is_insert = true;
            $model = new Article();
            $model->attributes = $_POST['Article'];
            if ($model->save()) {
                $insert_success = true;
                $message = "Saved Successfully!";
                DeviceController::sendPushNotifications("مقال جديد: " . $model->title_ar);
            } else {
                $message = json_encode($model->getErrors());
                // $message = "Error happed while insert the new data, Please try again!";
            }
        }

        return $this->render('AddArticle', ['is_insert'=>$is_insert,
            'insert_success'=>$insert_success,
            'message'=>$message]);
    }


    public function actionAddClinic()
    {
        $is_insert = false;
        $insert_success = false;
        $message = "";

        if (isset($_POST['Clinic']))
        {
            $is_insert = true;
            $model = new Clinic();
            $model->attributes = $_POST['Clinic'];
            if ($model->save()) {
                $insert_success = true;
                $message = "Saved Successfully!";
            } else {
                $message = json_encode($model->getErrors());
                // $message = "Error happed while insert the new data, Please try again!";
            }
        }

        return $this->render('AddClinic', ['is_insert'=>$is_insert,
            'insert_success'=>$insert_success,
            'message'=>$message]);
    }


    public function actionAddDepartment()
    {
        $is_insert = false;
        $insert_success = false;
        $message = "";

        if (isset($_POST['Department']))
        {
            $is_insert = true;
            $model = new Department();
            $model->attributes = $_POST['Department'];
            if ($model->save()) {
                $insert_success = true;
                $message = "Saved Successfully!";
            } else {
                $message = json_encode($model->getErrors());
                // $message = "Error happed while insert the new data, Please try again!";
            }
        }

        return $this->render('AddDepartment', ['is_insert'=>$is_insert,
            'insert_success'=>$insert_success,
            'message'=>$message]);
    }


    public function actionAddNews()
    {
        $is_insert = false;
        $insert_success = false;
        $message = "";


        if (isset($_POST['News']))
        {
            $is_insert = true;
            $model = new News();
            $model->attributes = $_POST['News'];

            $target_dir = "../news/";
            $ext = pathinfo($_FILES["image"]["name"], PATHINFO_EXTENSION);
            $model->image_name = date('Y-m-d|H-i-s', strtotime("now"))  . '.' . $ext;
            $target_file = $target_dir . $model->image_name;
            

            if (move_uploaded_file($_FILES["image"]["tmp_name"], $target_file)) {
                // echo "The file ". basename( $_FILES["fileToUpload"]["name"]). " has been uploaded.";
                if ($model->save()) {
                    $insert_success = true;
                    $message = "Saved Successfully!";
                    DeviceController::sendPushNotifications("خبر جديد: " . $model->title_ar);
                } else {
                    $message = json_encode($model->getErrors());
                    // $message = "Error happed while insert the new data, Please try again!";
                }
            } else {
                $message = "Sorry, there was an error uploading your file.";
            }

        }

        return $this->render('AddNews', ['is_insert'=>$is_insert,
            'insert_success'=>$insert_success,
            'message'=>$message]);
    }


    public function actionAddDoctor()
    {
        $is_insert = false;
        $insert_success = false;
        $message = "";


        if (isset($_POST['Doctor']))
        {
            $is_insert = true;
            $model = new Doctor();
            $model->attributes = $_POST['Doctor'];

            $target_dir = "../doctors/";
            $ext = pathinfo($_FILES["image"]["name"], PATHINFO_EXTENSION);
            $model->image_name = date('Y-m-d|H-i-s', strtotime("now"))  . '.' . $ext;
            $target_file = $target_dir . $model->image_name;
            

            if (move_uploaded_file($_FILES["image"]["tmp_name"], $target_file)) {
                // echo "The file ". basename( $_FILES["fileToUpload"]["name"]). " has been uploaded.";
                if ($model->save()) {
                    $insert_success = true;
                    $message = "Saved Successfully!";
                } else {
                    $message = json_encode($model->getErrors());
                    // $message = "Error happed while insert the new data, Please try again!";
                }
            } else {
                $message = "Sorry, there was an error uploading your file.";
            }

        }

        return $this->render('AddDoctor', ['is_insert'=>$is_insert,
            'insert_success'=>$insert_success,
            'message'=>$message]);
    }


    public function actionAddClient()
    {
        return $this->render('AddClient');
    }


    public function actionAddBanner()
    {
        return $this->render('AddBanner');
    }


    public function actionAddGallery()
    {
        return $this->render('AddGallery');
    }


    public function actionEditPreferences()
    {
        $is_insert = false;
        $insert_success = false;
        $message = "";

        $showVisitorsModel = Preferences::find()->where(['id' => 'show_visitors'])->one();

        if (isset($_POST['Preferences']))
        {
            $is_insert = true;
            $showVisitorsModel->value = $_POST['Preferences']['show_visitors'];

views/admin/AddBanner.php
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Add New <strong>Banner</strong>
  </h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-12">
          
        <p class="text-danger">* Recommended size is 1920 x 720</p>
        <form id="my-dropzone" action="../php/post_banner.php" class="dropzone box" style="height: 400px;" method="post">
            <div class="fallback">
                <input name="file" type="file" multiple />
            </div>
        </form>

    </div><!-- /.col-->
  </div><!-- ./row -->
</section><!-- /.content -->

views/admin/AddClient.php
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Add New <strong>Client</strong>
  </h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-12">
          
        <form action="../php/post_client.php" class="dropzone box" style="height: 400px;" method="post">
            <div class="fallback">
                <input name="file" type="file" multiple />
            </div>
        </form>

    </div><!-- /.col-->
  </div><!-- ./row -->
</section><!-- /.content -->

views/admin/AddGallery.php
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Add New <strong>Gallery Image</strong>
  </h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-12">
          
        <form id="my-dropzone" action="../php/post_gallery.php" class="dropzone box" style="height: 400px;" method="post">
            <div class="fallback">
                <input name="file" type="file" multiple />
            </div>
        </form>

    </div><!-- /.col-->
  </div><!-- ./row -->
</section><!-- /.content -->

views/admin/AllArticles.php
<?php
use yii\helpers\Url;
?>

<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    All Articles
    <a href="<?= Url::to(['admin/add-article']) ?>" class="btn btn-default"><span class="fa fa-plus"></span> Article</a>
  </h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-12">

      <div class="box">
        <div class="box-body">
          <table class="table table-bordered">
            
            <tr>
              <th style="width: 10px">#</th>
              <th>English Title</th>
              <th>Arabic Title</th>
              <th>English Content</th>
              <th>Arabic Content</th>
              <th style="width: 50px;">Actions</th>
            </tr>

            <?php
              $index = 0;
              foreach ($articles as $object) {
                  ?>

                  <tr>
                      <td><?= $index + 1 . '.' ?></td>
                      <td><?= $object->title_en ?></td>
                      <td><?= $object->title_ar ?></td>
                      <td><?= $object->content_en ?></td>
                      <td><?= $object->content_ar ?></td>

                      <td class="center">
                          <div class="btn-group">
                              <!-- <button type="submit" class="btn btn-xs btn-default"><span class="fa fa-pencil"></span></button> -->
                              <button type="button" href="#deleteDialog<?= $index ?>" data-toggle="modal" class="btn btn-xs btn-danger"><span class="fa fa-times"></span></button>
                          </div>
                      </td>
                  </tr>

                  <?php
                  $index++;
              }
            ?>

          </table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->

    </div><!-- /.col-->
  </div><!-- ./row -->
</section><!-- /.content -->
        

<?php
$index = 0;
foreach ($articles as $object) {
    ?>

    
    <div class="example-modal">
      <div class="modal" id="deleteDialog<?= $index ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Confirm Delete</h4>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to delete <strong><?= $object->title_en ?></strong>?</p>
            </div>

            <form action="<?= Url::to(['admin/all-articles']) ?>" method="post">

                <input type="number" name="deleteId" value="<?= $object->id ?>" hidden="true"/>

                <div class="modal-footer">
                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-danger">Delete</button>
                </div>

            </form>

          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    </div><!-- /.example-modal -->


    

    <?php
    $index++;
}
?>

views/admin/AllBanners.php
<?php
use yii\helpers\Url;
?>

<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    All Banners
    <a href="<?= Url::to(['admin/add-banner']) ?>" class="btn btn-default"><span class="fa fa-plus"></span> Banner</a>
  </h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-12">

      <div class="box">
        <div class="box-body">
          <table class="table table-bordered">

            <tr>
              <th style="width: 10px">#</th>
              <th>Title</th>
              <th style="width: 50px;">Actions</th>
            </tr>

            <?php
              $index = 0;
              $all_images = glob("../banners/*.{jpg,JPG,jpeg,JPEG,png,PNG}", GLOB_BRACE);
              foreach($all_images as $image) {
            ?>

            <tr>
              <td><?= $index + 1 . '.' ?></td>
              <td>
                <img height="100px" src="<?= Url::to([$image]) ?>" alt="Client Image">
              </td>
              <td>
                <button type="button" href="#deleteDialog<?= $index ?>" data-toggle="modal" class="btn btn-xs btn-danger"><span class="fa fa-times"></span></button>
              </td>
            </tr>

            <?php
                $index++;
              }
            ?>

          </table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->

    </div><!-- /.col-->
  </div><!-- ./row -->
</section><!-- /.content -->


<?php
$index = 0;
foreach ($all_images as $image) {
    ?>

    
    <div class="example-modal">
      <div class="modal" id="deleteDialog<?= $index ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Confirm Delete</h4>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to delete image #<strong><?= $index + 1 ?> <?= basename($image) ?></strong>?</p>
            </div>

            <form action="<?= Url::to(['admin/all-banners']) ?>" method="post">

                <input type="text" name="deleteFileName" value="<?= basename($image) ?>" hidden="true"/>

                <div class="modal-footer">
                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-danger">Delete</button>
                </div>

            </form>

          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    </div><!-- /.example-modal -->


    

    <?php
    $index++;
}
?>
        

views/admin/AllClients.php
<?php
use yii\helpers\Url;
?>

<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    All Clients
    <a href="<?= Url::to(['admin/add-client']) ?>" class="btn btn-default"><span class="fa fa-plus"></span> Client</a>
  </h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-12">

      <div class="box">
        <div class="box-body">
          <table class="table table-bordered">

            <tr>
              <th style="width: 10px">#</th>
              <th>Image</th>
              <th style="width: 50px;">Actions</th>
            </tr>

            <?php
              $index = 0;
              $all_images = glob("../clients/*.{jpg,JPG,jpeg,JPEG,png,PNG}", GLOB_BRACE);
              foreach($all_images as $image) {
            ?>

            <tr>
              <td><?= $index + 1 . '.' ?></td>
              <td>
                <img height="100px" src="<?= Url::to([$image]) ?>" alt="Client Image">
              </td>
              <td>
                <button type="button" href="#deleteDialog<?= $index ?>" data-toggle="modal" class="btn btn-xs btn-danger"><span class="fa fa-times"></span></button>
              </td>
            </tr>

            <?php
                $index++;
              }
            ?>

          </table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->

    </div><!-- /.col-->
  </div><!-- ./row -->
</section><!-- /.content -->


<?php
$index = 0;
foreach ($all_images as $image) {
    ?>

    
    <div class="example-modal">
      <div class="modal" id="deleteDialog<?= $index ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Confirm Delete</h4>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to delete image #<strong><?= $index + 1 ?> <?= basename($image) ?></strong>?</p>
            </div>

            <form action="<?= Url::to(['admin/all-clients']) ?>" method="post">

                <input type="text" name="deleteFileName" value="<?= basename($image) ?>" hidden="true"/>

                <div class="modal-footer">
                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-danger">Delete</button>
                </div>

            </form>

          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    </div><!-- /.example-modal -->


    

    <?php
    $index++;
}
?>
        

views/admin/AllClinics.php
<?php
use yii\helpers\Url;
?>

<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    All Clinics
    <a href="<?= Url::to(['admin/add-clinic']) ?>" class="btn btn-default"><span class="fa fa-plus"></span> Clinic</a>
  </h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-12">

      <div class="box">
        <div class="box-body">
          <table class="table table-bordered">
            
            <tr>
              <th style="width: 10px">#</th>
              <th>English Title</th>
              <th>Arabic Title</th>
              <th>English Content</th>
              <th>Arabic Content</th>
              <th style="width: 50px;">Actions</th>
            </tr>

            <?php
              $index = 0;
              foreach ($clinics as $object) {
                  ?>

                  <tr>
                      <td><?= $index + 1 . '.' ?></td>
                      <td><?= $object->title_en ?></td>
                      <td><?= $object->title_ar ?></td>
                      <td><?= $object->content_en ?></td>
                      <td><?= $object->content_ar ?></td>

                      <td class="center">
                          <div class="btn-group">
                            <button type="button" href="#deleteDialog<?= $index ?>" data-toggle="modal" class="btn btn-xs btn-danger"><span class="fa fa-times"></span></button>
                          </div>
                      </td>
                  </tr>

                  <?php
                  $index++;
              }
            ?>

          </table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->

    </div><!-- /.col-->
  </div><!-- ./row -->
</section><!-- /.content -->
        

<?php
$index = 0;
foreach ($clinics as $object) {
    ?>

    
    <div class="example-modal">
      <div class="modal" id="deleteDialog<?= $index ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Confirm Delete</h4>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to delete <strong><?= $object->title_en ?></strong>?</p>
            </div>

            <form action="<?= Url::to(['admin/all-clinics']) ?>" method="post">

                <input type="number" name="deleteId" value="<?= $object->id ?>" hidden="true"/>

                <div class="modal-footer">
                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-danger">Delete</button>
                </div>

            </form>

          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    </div><!-- /.example-modal -->


    

    <?php
    $index++;
}
?>

views/admin/AllDoctors.php
<?php
use yii\helpers\Url;
?>

<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    All Doctors
    <a href="<?= Url::to(['admin/add-doctor']) ?>" class="btn btn-default"><span class="fa fa-plus"></span> Doctor</a>
  </h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-12">

      <div class="box">
        <div class="box-body">
          <table class="table table-bordered">
            
            <tr>
              <th style="width: 10px">#</th>
              <th>English Name</th>
              <th>Arabic Name</th>
              <th>English Job Position</th>
              <th>Arabic Job Position</th>
              <th>English Working Hours</th>
              <th>Arabic Working Hours</th>
              <th>English Ext Doctor</th>
              <th>Arabic Ext Doctor</th>
              <th>Image</th>
              <th style="width: 30px;"><span class="fa fa-list"></span></th>
            </tr>

            <?php
              $index = 0;
              foreach ($doctors as $object) {
                  ?>

                  <tr>
                      <td><?= $index + 1 . '.' ?></td>
                      <td><?= $object->name_en ?></td>
                      <td><?= $object->name_ar ?></td>
                      <td><?= $object->job_position_en ?></td>
                      <td><?= $object->job_position_ar ?></td>
                      <td><?= $object->working_hours_en ?></td>
                      <td><?= $object->working_hours_ar ?></td>
                      <td><?= $object->ext_doctor_en ?></td>
                      <td><?= $object->ext_doctor_ar ?></td>
                      <td><img height="100px" src="<?= Url::to(['../doctors/' . $object->image_name]) ?>" alt="Doctor Image"></td>

                      <td class="center">
                          <div class="btn-group">
                            <button type="button" href="#deleteDialog<?= $index ?>" data-toggle="modal" class="btn btn-xs btn-danger"><span class="fa fa-times"></span></button>
                          </div>
                      </td>
                  </tr>

                  <?php
                  $index++;
              }
            ?>

          </table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->

    </div><!-- /.col-->
  </div><!-- ./row -->
</section><!-- /.content -->
        

<?php
$index = 0;
foreach ($doctors as $object) {
    ?>

    
    <div class="example-modal">
      <div class="modal" id="deleteDialog<?= $index ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Confirm Delete</h4>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to delete <strong><?= $object->name_en ?></strong>?</p>
            </div>

            <form action="<?= Url::to(['admin/all-doctors']) ?>" method="post">

                <input type="number" name="deleteId" value="<?= $object->id ?>" hidden="true"/>

                <div class="modal-footer">
                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-danger">Delete</button>
                </div>

            </form>

          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    </div><!-- /.example-modal -->


    

    <?php
    $index++;
}
?>

views/admin/AllGallery.php
<?php
use yii\helpers\Url;
?>

<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    All Gallery
    <a href="<?= Url::to(['admin/add-gallery']) ?>" class="btn btn-default"><span class="fa fa-plus"></span> Gallery Image</a>
  </h1>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-12">

      <div class="box">
        <div class="box-body">
          <table class="table table-bordered">

            <tr>
              <th style="width: 10px">#</th>
              <th>Image</th>
              <th style="width: 50px;">Actions</th>
            </tr>

            <?php
              $index = 0;
              $all_images = glob("../gallery/*.{jpg,JPG,jpeg,JPEG,png,PNG}", GLOB_BRACE);
              foreach($all_images as $image) {
            ?>

            <tr>
              <td><?= $index + 1 . '.' ?></td>
              <td>
                <img height="100px" src="<?= Url::to([$image]) ?>" alt="Gallery Image">
              </td>
              <td>
                <button type="button" href="#deleteDialog<?= $index ?>" data-toggle="modal" class="btn btn-xs btn-danger"><span class="fa fa-times"></span></button>
              </td>
            </tr>

            <?php
                $index++;
              }
            ?>

          </table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->

    </div><!-- /.col-->
  </div><!-- ./row -->
</section><!-- /.content -->


<?php
$index = 0;
foreach ($all_images as $image) {
    ?>

    
    <div class="example-modal">
      <div class="modal" id="deleteDialog<?= $index ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Confirm Delete</h4>
            </div>
            <div class="modal-body">
              <p>Are you sure you want to delete image #<strong><?= $index + 1 ?> <?= basename($image) ?></strong>?</p>
            </div>

            <form action="<?= Url::to(['admin/all-gallery']) ?>" method="post">

                <input type="text" name="deleteFileName" value="<?= basename($image) ?>" hidden="true"/>

                <div class="modal-footer">
                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-danger">Delete</button>
                </div>

            </form>

          </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    </div><!-- /.example-modal -->


    

    <?php
    $index++;
}
?>
        