controllers/AdminController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\User;

use app\models\Article;
use app\models\News;
use app\models\Clinic;
use app\models\Department;
use app\models\Doctor;
use app\models\Visit;
use app\models\Preferences;


class AdminController extends Controller
{

    public function beforeAction($action) {
        $this->enableCsrfValidation = false;

        /*if (\Yii::$app->user->isGuest) {
            return $this->redirect('login', 302);
        }*/

        return parent::beforeAction($action);
    }


    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => [
                            'logout',
                            'home',
                            'add-article',
                            'add-clinic',
                            'add-department',
                            'add-news',
                            'add-doctor',
                            'add-client',
                            'add-banner',
                            'add-gallery',
                            'edit-preferences',
                            'all-articles',
                            'all-clinics',
                            'all-departments',
                            'all-news',
                            'all-doctors',
                            'all-clients',
                            'all-banners',
                            'all-gallery',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->redirect('home', 302);
        }


        if(isset($_POST['User'])) {
            $username = $_POST['User']['username'];
            $password = $_POST['User']['password'];

            if ($username == 'admin' && $password == 'DPeMDhg9GF34zMJC') {
                $user = User::findByUsername($username);
                $res = Yii::$app->user->login($user, 3600*24*30);

                if ($res == true) {
                    return $this->redirect('home', 302);
                }
            }
        }

        $this->layout = 'empty';
        return $this->render('login');
    }


    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect('login', 302);
    }


    public function actionHome()
    {
        // DeviceController::sendPushNotifications("Test Notification");

        $articles_count = Article::find()->count();
        $news_count = News::find()->count();
        $clinics_count = Clinic::find()->count();
        $departments_count = Department::find()->count();
        $doctors_count = Doctor::find()->count();
        $visits_count = Visit::find()->count();

        $clients_count = count(glob("../../clients/*.{jpg,png,gif}", GLOB_BRACE));
        $banners_count = count(glob("../../banners/*.{jpg,png,gif}", GLOB_BRACE));
        
        return $this->render('Home', [
            'articles_count' => $articles_count,
            'news_count' => $news_count,
            'clinics_count' => $clinics_count,
            'departments_count' => $departments_count,
            'doctors_count' => $doctors_count,
            'visits_count' => $visits_count,
            'clients_count' => $clients_count,
            'banners_count' => $banners_count,
        ]);
    }


    public function actionAddArticle()
    {
        $is_insert = false;
        $insert_success = false;
        $message = "";

        if (isset($_POST['Article']))
        {
            $is_insert = true;
            $model = new Article();
            $model->attributes = $_POST['Article'];
            if ($model->save()) {
                $insert_success = true;
                $message = "Saved Successfully!";
                DeviceController::sendPushNotifications("مقال جديد: " . $model->title_ar);
            } else {
                $message = json_encode($model->getErrors());
                // $message = "Error happed while insert the new data, Please try again!";
            }
        }

        return $this->render('AddArticle', ['is_insert'=>$is_insert,
            'insert_success'=>$insert_success,
            'message'=>$message]);
    }


    public function actionAddClinic()
    {
        $is_insert = false;
        $insert_success = false;
        $message = "";

        if (isset($_POST['Clinic']))
        {
            $is_insert = true;
            $model = new Clinic();
            $model->attributes = $_POST['Clinic'];
            if ($model->save()) {
                $insert_success = true;
                $message = "Saved Successfully!";
            } else {
                $message = json_encode($model->getErrors());
                // $message = "Error happed while insert the new data, Please try again!";
            }
        }

        return $this->render('AddClinic', ['is_insert'=>$is_insert,
            'insert_success'=>$insert_success,
            'message'=>$message]);
    }


    public function actionAddDepartment()
    {
        $is_insert = false;
        $insert_success = false;
        $message = "";

        if (isset($_POST['Department']))
        {
            $is_insert = true;
            $model = new Department();
            $model->attributes = $_POST['Department'];
            if ($model->save()) {
                $insert_success = true;
                $message = "Saved Successfully!";
            } else {
                $message = json_encode($model->getErrors());
                // $message = "Error happed while insert the new data, Please try again!";
            }
        }

        return $this->render('AddDepartment', ['is_insert'=>$is_insert,
            'insert_success'=>$insert_success,
            'message'=>$message]);
    }


    public function actionAddNews()
    {
        $is_insert = false;
        $insert_success = false;
        $message = "";


        if (isset($_POST['News']))
        {
            $is_insert = true;
            $model = new News();
            $model->attributes = $_POST['News'];

            $target_dir = "../news/";
            $ext = pathinfo($_FILES["image"]["name"], PATHINFO_EXTENSION);
            $model->image_name = date('Y-m-d|H-i-s', strtotime("now"))  . '.' . $ext;
            $target_file = $target_dir . $model->image_name;
            

            if (move_uploaded_file($_FILES["image"]["tmp_name"], $target_file)) {
                // echo "The file ". basename( $_FILES["fileToUpload"]["name"]). " has been uploaded.";
                if ($model->save()) {
                    $insert_success = true;
                    $message = "Saved Successfully!";
                    DeviceController::sendPushNotifications("خبر جديد: " . $model->title_ar);
                } else {
                    $message = json_encode($model->getErrors());
                    // $message = "Error happed while insert the new data, Please try again!";
                }
            } else {
                $message = "Sorry, there was an error uploading your file.";
            }

        }

        return $this->render('AddNews', ['is_insert'=>$is_insert,
            'insert_success'=>$insert_success,
            'message'=>$message]);
    }


    public function actionAddDoctor()
    {
        $is_insert = false;
        $insert_success = false;
        $message = "";


        if (isset($_POST['Doctor']))
        {
            $is_insert = true;
            $model = new Doctor();
            $model->attributes = $_POST['Doctor'];

            $target_dir = "../doctors/";
            $ext = pathinfo($_FILES["image"]["name"], PATHINFO_EXTENSION);
            $model->image_name = date('Y-m-d|H-i-s', strtotime("now"))  . '.' . $ext;
            $target_file = $target_dir . $model->image_name;
            

            if (move_uploaded_file($_FILES["image"]["tmp_name"], $target_file)) {
                // echo "The file ". basename( $_FILES["fileToUpload"]["name"]). " has been uploaded.";
                if ($model->save()) {
                    $insert_success = true;
                    $message = "Saved Successfully!";
                } else {
                    $message = json_encode($model->getErrors());
                    // $message = "Error happed while insert the new data, Please try again!";
                }
            } else {
                $message = "Sorry, there was an error uploading your file.";
            }

        }

        return $this->render('AddDoctor', ['is_insert'=>$is_insert,
            'insert_success'=>$insert_success,
            'message'=>$message]);
    }


    public function actionAddClient()
    {
        return $this->render('AddClient');
    }


    public function actionAddBanner()
    {
        return $this->render('AddBanner');
    }


    public function actionAddGallery()
    {
        return $this->render('AddGallery');
    }


    public function actionEditPreferences()
    {
        $is_insert = false;
        $insert_success = false;
        $message = "";

        $showVisitorsModel = Preferences::find()->where(['id' => 'show_visitors'])->one();

        if (isset($_POST['Preferences']))
        {
            $is_insert = true;
            $showVisitorsModel->value = $_POST['Preferences']['show_visitors'];

controllers/ArController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

use app\models\Article;
use app\models\News;
use app\models\Clinic;
use app\models\Department;
use app\models\Doctor;
use app\models\Visit;


class ArController extends Controller
{

    public function actionHome()
    {
        $visit = new Visit();
        $visit->save();

        $this->layout = 'ar';

        $news = News::find()->limit(4)->orderBy(['id' => SORT_DESC])->all();
        $articles = Article::find()->limit(10)->orderBy(['id' => SORT_DESC])->all();

        return $this->render('Home', [
            'news' => $news,
            'articles' => $articles,
        ]);
    }


    public function actionClinics()
    {
        $this->layout = 'ar';

        $clinics = Clinic::find()->all();
        return $this->render('Clinics', [
            'clinics' => $clinics
        ]);
    }


    public function actionDepartments()
    {
        $this->layout = 'ar';

        $departments = Department::find()->all();
        return $this->render('Departments', [
            'departments' => $departments
        ]);
    }


    public function actionGallery()
    {
        $this->layout = 'ar';
        return $this->render('Gallery');
    }


    public function actionAbout()
    {
        $this->layout = 'ar';
        $doctors = Doctor::find()->all();
        return $this->render('About', [
            'doctors' => $doctors
        ]);
    }


    public function actionContact()
    {
        $this->layout = 'ar';
        return $this->render('Contact');
    }


    public function actionAllNews()
    {
        $this->layout = 'ar';

        $news = News::find()->orderBy(['id' => SORT_DESC])->all();
        return $this->render('AllNews', [
            'news' => $news,
        ]);
    }


    public function actionNews()
    {
        if (isset($_GET['id']))
        {
            $this->layout = 'ar';

            $news = News::find()->where(["id" => $_GET['id']])->one();
            return $this->render('News', [
                'news' => $news,
            ]);
        }
        
        return $this->redirect(Yii::$app->request->referrer);
    }


    public function actionAllArticles()
    {
        $this->layout = 'ar';

        $articles = Article::find()->orderBy(['id' => SORT_DESC])->all();
        return $this->render('AllArticles', [
            'articles' => $articles,
        ]);
    }
    
}

controllers/EnController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

use app\models\Article;
use app\models\News;
use app\models\Clinic;
use app\models\Department;
use app\models\Doctor;
use app\models\Visit;


class EnController extends Controller
{

    public function actionHome()
    {
        $visit = new Visit();
        $visit->save();

        $this->layout = 'en';

        $news = News::find()->limit(4)->orderBy(['id' => SORT_DESC])->all();
        $articles = Article::find()->limit(10)->orderBy(['id' => SORT_DESC])->all();

        return $this->render('Home', [
            'news' => $news,
            'articles' => $articles,
        ]);
    }


    public function actionClinics()
    {
        $this->layout = 'en';

        $clinics = Clinic::find()->all();
        return $this->render('Clinics', [
            'clinics' => $clinics
        ]);
    }


    public function actionDepartments()
    {
        $this->layout = 'en';

        $departments = Department::find()->all();
        return $this->render('Departments', [
            'departments' => $departments
        ]);
    }


    public function actionGallery()
    {
        $this->layout = 'en';
        return $this->render('Gallery');
    }


    public function actionAbout()
    {
        $this->layout = 'en';
        $doctors = Doctor::find()->all();
        return $this->render('About', [
            'doctors' => $doctors
        ]);
    }


    public function actionContact()
    {
        $this->layout = 'en';
        return $this->render('Contact');
    }


    public function actionAllNews()
    {
        $this->layout = 'en';

        $news = News::find()->orderBy(['id' => SORT_DESC])->all();
        return $this->render('AllNews', [
            'news' => $news,
        ]);
    }


    public function actionNews()
    {
        if (isset($_GET['id']))
        {
            $this->layout = 'en';

            $news = News::find()->where(["id" => $_GET['id']])->one();
            return $this->render('News', [
                'news' => $news,
            ]);
        }
        
        return $this->redirect(Yii::$app->request->referrer);
    }


    public function actionAllArticles()
    {
        $this->layout = 'en';

        $articles = Article::find()->orderBy(['id' => SORT_DESC])->all();
        return $this->render('AllArticles', [
            'articles' => $articles,
        ]);
    }
    
}

views/layouts/ar.php
<?php
use yii\helpers\Url;
?>

<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <base href="" />
	<!-- Basic Page Needs

     ================================================== -->
	 
	 <meta charset="utf-8">
	 
	 <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    
	 <link rel="icon" type="image/png" href="<?= Url::to(['ar/images/favicon.png']) ?>">
	
     <title>عيادات عناية المستقبل</title>
    
     <meta name="description" content="عيادات عناية المستقبل">
    
     <meta name="keywords" content="عيادات عناية المستقبل">
    
     <meta name="author" content="araa.com.sa">

	 
	 <!-- Mobile Specific Metas
    
     ================================================== -->
    
     <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    
     <meta name="format-detection" content="telephone=no">

	 
	 <!-- Web Font
	 ============================================= -->
	 <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800" rel="stylesheet">
	
	
	<!-- CSS
    
     ================================================== -->
	 
	 
	<!-- Theme Color
	============================================= -->
	<link rel="stylesheet" id="color" href="<?= Url::to(['ar/css/blue.css']) ?>">
    
	
	<!-- Medicom Style
	============================================= -->
    <link rel="stylesheet" href="<?= Url::to(['ar/css/medicom.css']) ?>">

	
	<!-- This page
	============================================= -->
    <link href="<?= Url::to(['ar/css/revolution_style.css']) ?>" rel="stylesheet">
	<link href="<?= Url::to(['ar/css/settings.css']) ?>" rel="stylesheet">
	
	
	<!-- Bootstrap
	============================================= -->
    <link rel="stylesheet" href="<?= Url::to(['ar/css/bootstrap.css']) ?>">

    
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

	
	
	<!-- Header Scripts
    
    ================================================== -->
	
	<script src="<?= Url::to(['ar/js/modernizr-2.6.2.min.js']) ?>"></script>
	
	
	</head>
    <body class="fixed-header">
		
		
		
    
		<!-- Document Wrapper
		============================================= -->
		<div id="wrapper" class="clearfix">
    
		
		<!-- Header
		============================================= -->
		<header id="header" class="medicom-header">
		
			<!-- Top Row
			============================================= -->
			<div class="solid-row"></div>
        
			<div class="container">
				
				
				<!-- Primary Navigation
				============================================= -->
				<nav class="navbar navbar-default" role="navigation">
				
					<!-- Brand and toggle get grouped for better mobile display
					============================================= -->
					
					<div class="navbar-header">
						
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#primary-nav">
						  <span class="sr-only">Toggle navigation</span>
						  <span class="icon-bar"></span>
						  <span class="icon-bar"></span>
						  <span class="icon-bar"></span>
						</button>
						
						<a class="navbar-brand" href="index.php"><img src="<?= Url::to(['ar/images/logo.png']) ?>" alt="" title=""></a>
					
					</div>
				
					
					<div class="collapse navbar-collapse navbar-left" id="primary-nav">
						
						<ul class="nav navbar-nav">
							
							<li>
								<a href="<?= Url::to(['ar/home']) ?>">
									<i class="fa fa-home"></i> الرئيسية
								</a>
							</li>

							<li>
								<a href="<?= Url::to(['ar/clinics']) ?>">
									<i class="fa fa-hospital-o"></i> العيادات
								</a>
							</li>

							<li>
								<a href="<?= Url::to(['ar/departments']) ?>">
									<i class="fa fa-sitemap"></i> الأقسام
								</a>
							</li>

							<li>
								<a href="<?= Url::to(['ar/gallery']) ?>">
									<i class="fa fa-picture-o"></i> المعرض
								</a>
							</li>

							<li>
								<a href="<?= Url::to(['ar/about']) ?>">
									<i class="fa fa-info-circle"></i> عن العيادات
								</a>
							</li>

							<li>
								<a href="<?= Url::to(['ar/contact']) ?>">
									<i class="fa fa-envelope"></i> الاتصال
								</a>
							</li>

							<li><a href="<?= Url::to(['en/home']) ?>"><strong>English</strong></a></li>
						  
						</ul>
						
					</div>
					
				</nav>

			</div>

    </header>

	
	
    <div id="content-index">
    
	
		<?= $content ?>

    
    </div><!--end #content-index-->
    
    
	
		
		<!-- back to top -->
		<a href="#." class="back-to-top" id="back-to-top"><i class="fa fa-angle-up"></i></a>
	
    </div><!--end #wrapper-->


    <div class="colourfull-row" style="padding: 0;  margin: 0;"></div>

    <!-- Copyright
	============================================= -->
	<?php
		use app\models\Visit;
		use app\models\Preferences;

		$visits_count = Visit::find()->count();
        $showVisitors = Preferences::find()->where(['id' => 'show_visitors'])->one();
        if ($showVisitors->value == 1) {
	?>
		<p class="text-center" style="background:#f5f5f5; border-bottom:1px solid #e6e6e6; color:#646464; margin:0; font-size: 12px; padding:10px 0 8px;">عدد زوار الموقع: <span><?= $visits_count ?></span> </p>
	<?php
	}
	?>

    <p class="text-center" style="background:#f5f5f5; border-bottom:1px solid #e6e6e6; color:#646464; margin:0; font-size: 12px; padding:10px 0 8px;">حقوق النشر &copy; 2016 <a href="http://araa.com.sa">آراء ميديا</a>. جميع الحقوق محفوظة.</p>
	
    
	
	<!-- All Javascript 
	============================================= -->
	<script src="<?= Url::to(['ar/js/jquery.js']) ?>"></script>
    <script src="<?= Url::to(['ar/js/bootstrap.min.js']) ?>"></script>
    <script src="<?= Url::to(['ar/js/jquery.stellar.js']) ?>"></script>
	<script src="<?= Url::to(['ar/js/jquery-ui-1.10.3.custom.js']) ?>"></script>
    <script src="<?= Url::to(['ar/js/owl.carousel.js']) ?>"></script>
    <script src="<?= Url::to(['ar/js/counter.js']) ?>"></script>
    <script src="<?= Url::to(['ar/js/waypoints.js']) ?>"></script>
	<script src="<?= Url::to(['ar/js/jquery.uniform.js']) ?>"></script>
    <script src="<?= Url::to(['ar/js/easyResponsiveTabs.js']) ?>"></script>
	<script src="<?= Url::to(['ar/js/jquery.fancybox.pack.js']) ?>"></script>
	<script src="<?= Url::to(['ar/js/jquery.fancybox-media.js']) ?>"></script>
	<script src="<?= Url::to(['ar/js/jquery.mixitup.js']) ?>"></script>
	<script src="<?= Url::to(['ar/js/forms-validation.js']) ?>"></script>
	<script src="<?= Url::to(['ar/js/jquery.jcarousel.min.js']) ?>"></script>
	<script src="<?= Url::to(['ar/js/jquery.easypiechart.min.js']) ?>"></script>
	<script src="<?= Url::to(['ar/js/scripts.js']) ?>"></script>
    
	<!-- This page
	============================================= -->
	<script src="<?= Url::to(['ar/js/jquery.themepunch.plugins.min.js']) ?>"></script>			
    <script src="<?= Url::to(['ar/js/jquery.themepunch.revolution.min.js']) ?>"></script>
    
	
	<script>
	
		(function () {
			
			// Revolution slider
			var revapi;
			revapi = jQuery('.fullwidthabnner').revolution(
			{
				delay:9000,
				startwidth:1920,
				startheight:720,
				hideThumbs:200,
				fullWidth:"on",
				forceFullWidth:"on"
			});
			
		})();

	</script>
	
  </body>
</html>

views/layouts/empty.php
<?= $content ?>

views/layouts/en.php
<?php
use yii\helpers\Url;
?>


<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <base href="" />
	<!-- Basic Page Needs

     ================================================== -->
	 
	 <meta charset="utf-8">
	 
	 <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    
	 <link rel="icon" type="image/png" href="<?= Url::to(['en/images/favicon.png']) ?>">
	
     <title>Future Care Clinics</title>
    
     <meta name="description" content="Future Care Clinics">
    
     <meta name="keywords" content="Future Care Clinics">
    
     <meta name="author" content="araa.com.sa">

	 
	 <!-- Mobile Specific Metas
    
     ================================================== -->
    
     <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    
     <meta name="format-detection" content="telephone=no">

	 
	 <!-- Web Font
	 ============================================= -->
	 <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800" rel="stylesheet">
	
	
	<!-- CSS
    
     ================================================== -->
	 
	 
	<!-- Theme Color
	============================================= -->
	<link rel="stylesheet" id="color" href="<?= Url::to(['en/css/blue.css']) ?>">
    
	
	<!-- Medicom Style
	============================================= -->
    <link rel="stylesheet" href="<?= Url::to(['en/css/medicom.css']) ?>">

	
	<!-- This page
	============================================= -->
    <link href="<?= Url::to(['en/css/revolution_style.css']) ?>" rel="stylesheet">
	<link href="<?= Url::to(['en/css/settings.css']) ?>" rel="stylesheet">
	
	
	<!-- Bootstrap
	============================================= -->
    <link rel="stylesheet" href="<?= Url::to(['en/css/bootstrap.css']) ?>">

    
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

	
	
	<!-- Header Scripts
    
    ================================================== -->
	
	<script src="<?= Url::to(['en/js/modernizr-2.6.2.min.js']) ?>"></script>
	
	
	</head>
    <body class="fixed-header">
		
		
		
    
		<!-- Document Wrapper
		============================================= -->
		<div id="wrapper" class="clearfix">
    
		
		<!-- Header
		============================================= -->
		<header id="header" class="medicom-header">
		
			<!-- Top Row
			============================================= -->
			<div class="solid-row"></div>
        
			<div class="container">
				
				
				<!-- Primary Navigation
				============================================= -->
				<nav class="navbar navbar-default" role="navigation">
				
					<!-- Brand and toggle get grouped for better mobile display
					============================================= -->
					
					<div class="navbar-header">
						
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#primary-nav">
						  <span class="sr-only">Toggle navigation</span>
						  <span class="icon-bar"></span>
						  <span class="icon-bar"></span>
						  <span class="icon-bar"></span>
						</button>
						
						<a class="navbar-brand" href="index.php"><img src="<?= Url::to(['en/images/logo.png']) ?>" alt="" title=""></a>
					
					</div>
				
					
					<div class="collapse navbar-collapse navbar-right" id="primary-nav">
						
						<ul class="nav navbar-nav">
							
							<li>
								<a href="<?= Url::to(['en/home']) ?>">
									<i class="fa fa-home"></i> Home
								</a>
							</li>

							<li>
								<a href="<?= Url::to(['en/clinics']) ?>">
									<i class="fa fa-hospital-o"></i> Clinics
								</a>
							</li>

							<li>
								<a href="<?= Url::to(['en/departments']) ?>">
									<i class="fa fa-sitemap"></i> Departments
								</a>
							</li>

							<li>
								<a href="<?= Url::to(['en/gallery']) ?>">
									<i class="fa fa-picture-o"></i> Gallery
								</a>
							</li>

							<li>
								<a href="<?= Url::to(['en/about']) ?>">
									<i class="fa fa-info-circle"></i> About
								</a>
							</li>

							<li>
								<a href="<?= Url::to(['en/contact']) ?>">
									<i class="fa fa-envelope"></i> Contact
								</a>
							</li>

							<li><a href="<?= Url::to(['ar/home']) ?>"><strong>العربية</strong></a></li>
						  
						</ul>
						
					</div>
					
				</nav>

			</div>

    </header>

	
	
    <div id="content-index">
    
	
		<?= $content ?>

    
    </div><!--end #content-index-->
    
    
	
		
		<!-- back to top -->
		<a href="#." class="back-to-top" id="back-to-top"><i class="fa fa-angle-up"></i></a>
	
    </div><!--end #wrapper-->


    <div class="colourfull-row" style="padding: 0;  margin: 0;"></div>

    <!-- Copyright
	============================================= -->
	<?php
		use app\models\Visit;
		use app\models\Preferences;

		$visits_count = Visit::find()->count();
        $showVisitors = Preferences::find()->where(['id' => 'show_visitors'])->one();
        if ($showVisitors->value == 1) {
	?>
		<p class="text-center" style="background:#f5f5f5; border-bottom:1px solid #e6e6e6; color:#646464; margin:0; font-size: 12px; padding:10px 0 8px;">Number of visitors: <span><?= $visits_count ?></span> </p>
	<?php
	}
	?>

    <p class="text-center" style="background:#f5f5f5; border-bottom:1px solid #e6e6e6; color:#646464; margin:0; font-size: 12px; padding:10px 0 8px;">Copyright &copy; 2016 <a href="http://araa.com.sa">Araa Media</a>. All right reserved.</p>
	
    
	
	<!-- All Javascript 
	============================================= -->
	<script src="<?= Url::to(['en/js/jquery.js']) ?>"></script>
    <script src="<?= Url::to(['en/js/bootstrap.min.js']) ?>"></script>
    <script src="<?= Url::to(['en/js/jquery.stellar.js']) ?>"></script>
	<script src="<?= Url::to(['en/js/jquery-ui-1.10.3.custom.js']) ?>"></script>
    <script src="<?= Url::to(['en/js/owl.carousel.js']) ?>"></script>
    <script src="<?= Url::to(['en/js/counter.js']) ?>"></script>
    <script src="<?= Url::to(['en/js/waypoints.js']) ?>"></script>
	<script src="<?= Url::to(['en/js/jquery.uniform.js']) ?>"></script>
    <script src="<?= Url::to(['en/js/easyResponsiveTabs.js']) ?>"></script>
	<script src="<?= Url::to(['en/js/jquery.fancybox.pack.js']) ?>"></script>
	<script src="<?= Url::to(['en/js/jquery.fancybox-media.js']) ?>"></script>
	<script src="<?= Url::to(['en/js/jquery.mixitup.js']) ?>"></script>
	<script src="<?= Url::to(['en/js/forms-validation.js']) ?>"></script>
	<script src="<?= Url::to(['en/js/jquery.jcarousel.min.js']) ?>"></script>
	<script src="<?= Url::to(['en/js/jquery.easypiechart.min.js']) ?>"></script>
	<script src="<?= Url::to(['en/js/scripts.js']) ?>"></script>
    
	<!-- This page
	============================================= -->
	<script src="<?= Url::to(['en/js/jquery.themepunch.plugins.min.js']) ?>"></script>			
    <script src="<?= Url::to(['en/js/jquery.themepunch.revolution.min.js']) ?>"></script>
    
	
	<script>
	
		(function () {
			
			// Revolution slider
			var revapi;
			revapi = jQuery('.fullwidthabnner').revolution(
			{
				delay:9000,
				startwidth:1920,
				startheight:720,
				hideThumbs:200,
				fullWidth:"on",
				forceFullWidth:"on"
			});
			
		})();

	</script>
	
  </body>
</html>