controllers/EnController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

use app\models\Article;
use app\models\News;
use app\models\Clinic;
use app\models\Department;
use app\models\Doctor;
use app\models\Visit;


class EnController extends Controller
{

    public function actionHome()
    {
        $visit = new Visit();
        $visit->save();

        $this->layout = 'en';

        $news = News::find()->limit(4)->orderBy(['id' => SORT_DESC])->all();
        $articles = Article::find()->limit(10)->orderBy(['id' => SORT_DESC])->all();

        return $this->render('Home', [
            'news' => $news,
            'articles' => $articles,
        ]);
    }


    public function actionClinics()
    {
        $this->layout = 'en';

        $clinics = Clinic::find()->all();
        return $this->render('Clinics', [
            'clinics' => $clinics
        ]);
    }


    public function actionDepartments()
    {
        $this->layout = 'en';

        $departments = Department::find()->all();
        return $this->render('Departments', [
            'departments' => $departments
        ]);
    }


    public function actionGallery()
    {
        $this->layout = 'en';
        return $this->render('Gallery');
    }


    public function actionAbout()
    {
        $this->layout = 'en';
        $doctors = Doctor::find()->all();
        return $this->render('About', [
            'doctors' => $doctors
        ]);
    }


    public function actionContact()
    {
        $this->layout = 'en';
        return $this->render('Contact');
    }


    public function actionAllNews()
    {
        $this->layout = 'en';

        $news = News::find()->orderBy(['id' => SORT_DESC])->all();
        return $this->render('AllNews', [
            'news' => $news,
        ]);
    }


    public function actionNews()
    {
        if (isset($_GET['id']))
        {
            $this->layout = 'en';

            $news = News::find()->where(["id" => $_GET['id']])->one();
            return $this->render('News', [
                'news' => $news,
            ]);
        }
        
        return $this->redirect(Yii::$app->request->referrer);
    }


    public function actionAllArticles()
    {
        $this->layout = 'en';

        $articles = Article::find()->orderBy(['id' => SORT_DESC])->all();
        return $this->render('AllArticles', [
            'articles' => $articles,
        ]);
    }
    
}

views/en/About.php
<?php
use yii\helpers\Url;
?>

<!-- Sub Page Banner
============================================= -->
<section class="sub-page-banner text-center" data-stellar-background-ratio="0.3" style="background: url(<?= Url::to(['en/images/about-banner.jpg']) ?>) no-repeat center">
	
	<div class="overlay"></div>
	
	<div class="container">
		<h1 class="entry-title">about us</h1>
		<p></p>
	</div>
	
</section>



<!-- Sub Page Content
============================================= -->
<div id="sub-page-content">


<div class="container big-font">
	
	<h2 class="light bordered main-title">who <span>we are</span></h2>

	<div class="row">

    	<div class="col-md-6">
        	<p class="footer-bottom-text">Future Care Clinics is the first and largest integrated in the area. Doctors from every medical specialty work together to care for patients, joined by common systems and a philosophy of "the needs of the patient come first".<br><br>
        	<strong>Mission & Value:</strong> Will provide the best care to every patient every day through integrated clinical practice.<br><br>
        	<strong>Primary Value:</strong> The needs of the patient come first.</p>
        </div>
        
        <div class="col-md-6">
			<!-- Toggle Styles
			============================================= -->
			<h5>Core Principles</h5>

			<div class="panel-group accordian-style2" id="principles">

				<div class="panel panel-default">
					<div class="panel-heading">
						<h5 class="panel-title">
							<a data-toggle="collapse" data-parent="#principles" href="#principles1">
								<i class="fa fa-medkit"></i>Practice<i class="fa fa-angle-up pull-right"></i>
							</a>
						</h5>
					</div>
						
					<div id="principles1" class="panel-collapse collapse">
						<div class="panel-body">
							Practice medicine as an integrated team of compassionate, multi-disciplinary physicians,  and allied health professionals who are focused on the needs of patients from our communities and regions.
						</div>
					</div>
						
				</div>
				
				<div class="panel panel-default">
					<div class="panel-heading">
						<h5 class="panel-title">
							<a data-toggle="collapse" data-parent="#principles" href="#principles2">
								<i class="fa fa-medkit"></i>Education<i class="fa fa-angle-up pull-right"></i>
							</a>
						</h5>
					</div>
						
					<div id="principles2" class="panel-collapse collapse">
						<div class="panel-body">
							Educate physicians, scientists and allied health professionals and be a dependable source of health information for our patients and the public.
						</div>
					</div>
						
				</div>

				<div class="panel panel-default">
					<div class="panel-heading">
						<h5 class="panel-title">
							<a data-toggle="collapse" data-parent="#principles" href="#principles3">
								<i class="fa fa-medkit"></i>Mutual Respect<i class="fa fa-angle-up pull-right"></i>
							</a>
						</h5>
					</div>
						
					<div id="principles3" class="panel-collapse collapse">
						<div class="panel-body">
							Treat everyone in our diverse community with respect and dignity.
						</div>
					</div>
						
				</div>

				<div class="panel panel-default">
					<div class="panel-heading">
						<h5 class="panel-title">
							<a data-toggle="collapse" data-parent="#principles" href="#principles4">
								<i class="fa fa-medkit"></i>Commitment to Quality<i class="fa fa-angle-up pull-right"></i>
							</a>
						</h5>
					</div>
						
					<div id="principles4" class="panel-collapse collapse">
						<div class="panel-body">
							Continuously improve all processes that support patient care and education.
						</div>
					</div>
						
				</div>

				<div class="panel panel-default">
					<div class="panel-heading">
						<h5 class="panel-title">
							<a data-toggle="collapse" data-parent="#principles" href="#principles5">
								<i class="fa fa-medkit"></i>Work Atmosphere<i class="fa fa-angle-up pull-right"></i>
							</a>
						</h5>
					</div>
						
					<div id="principles5" class="panel-collapse collapse">
						<div class="panel-body">
							Foster teamwork, personal responsibility, integrity, innovation, trust and communication within the context of a physician-led institution.
						</div>
					</div>
						
				</div>

				<div class="panel panel-default">
					<div class="panel-heading">
						<h5 class="panel-title">
							<a data-toggle="collapse" data-parent="#principles" href="#principles6">
								<i class="fa fa-medkit"></i>Societal Commitment<i class="fa fa-angle-up pull-right"></i>
							</a>
						</h5>
					</div>
						
					<div id="principles6" class="panel-collapse collapse">
						<div class="panel-body">
							Benefit humanity through patient care and education. Support the communities in which we live and work. Serve appropriately patients in difficult financial circumstances.
						</div>
					</div>
						
				</div>

			</div>	
		</div>

    </div>
	

</div>


<div class="height20"></div>


<!-- Team
============================================= -->
<section class="testimonials bg-white text-center">
	
	<div class="container">
		
		<div class="text-center">
			<h1 class="light">meet the <span>perfect specialists</span> team</h1>
		</div>
		
		<div class="height50"></div>
		
		<div id="carousel-testimonials" class="owl-carousel slide testimonials-carousel">
			

			<?php
				foreach($doctors as $object) {
					echo '<div class="team-member">';
					echo '<div class="team-thumb">';
					echo '<img src="' . Url::to(['../doctors/' . $object->image_name]) . '" class="img-rounded" alt="">';
					echo '</div>';
					echo '<h5 style="color: #552f7c;">'. $object->name_en .'</h5>';
					echo '<h5><span>'. $object->job_position_en .'</span></h5>';
					echo '<p class="text-center">'. $object->working_hours_en .'</p>';
					echo '<p class="text-center">'. $object->ext_doctor_en .'</p>';
					echo '</div>';
				}
			?>

			
		 </div>

	</div>
	
	<div class="height50"></div>
	
</section>

views/en/AllArticles.php
<!-- Articles
============================================= -->
<section class="latest-news">

	<div class="container">
	
		<div class="row">
			
			
			<!-- Sidebar
			============================================= -->
			<aside class="col-md-12">
				
				<h2 class="bordered light">Health <span>Advise</span></h2>
				<div class="panel-group" id="accordion">


					<?php
						$index = 0;
		        		foreach($articles as $article) {
		        	?>

					<div class="panel panel-default">
						<div class="panel-heading">
						  <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapse<?= $index ?>">
							  <span><i class="fa fa-plus"></i></span><?= $article->title_en ?>
							</a>
						  </h4>
						</div>
						<div id="collapse<?= $index ?>" class="panel-collapse collapse">
						  <div class="panel-body">
						   <?= $article->content_en ?>
						  </div>
						</div>
					  </div>

		        	<?php
		        			$index++;
		        		}
		        	?>

				  
				</div>
			
			</aside>
			
		</div>
		
	</div>
	
</section>

views/en/AllNews.php
<?php
use yii\helpers\Url;
?>

<!-- Latest News
============================================= -->
<section class="latest-news">

	<div class="container">
	
		<div class="row">
			
			<div class="col-md-12">
				
				<h2 class="bordered light">Latest <span>News</span></h2>
				
				<div class="row">

					<?php
		        		foreach($news as $news_object) {
		        			$timestamp = strtotime($news_object->created_at);
		        			$year = date('Y', $timestamp); // 1-7
							$month = date('M', $timestamp); // 1-12
							$day = date('d', $timestamp); // 1-31
		        	?>

		        	<div class="col-md-6">
						<article class="blog-item">
							<div class="blog-thumbnail">
								<div class="blog-date"><p class="day"><?= $day ?></p><p class="monthyear"><?= $month . ' ' . $year ?></p></div>
								<img src="<?= Url::to(['../news/' . $news_object->image_name]) ?>" alt="" title="News Image">
							</div>
							<div class="blog-content">
								<h4 class="blog-title"><a href="<?= Url::to(['en/news?id=' . $news_object->id]) ?>"><?= $news_object->title_en ?></a></h4>
								<p><?= $news_object->content_en ?></p>
							</div>
						</article>	
					</div>

		        	<?php
		        		}
		        	?>
					
					
				</div>
				
			</div>
			
		</div>
		
	</div>
	
</section>

views/en/Clinics.php
<?php
use yii\helpers\Url;
?>

<!-- Sub Page Content
============================================= -->
<div id="sub-page-content" class="clearfix">

	<div class="container">
		
		<div class="row">
		
			<div class="col-md-12 blog-wrapper clearfix">
				
				<h2 class="bordered light">Clinics</h2>
				
				<article class="blog-item blog-full-width blog-detail">
					
					<div class="blog-thumbnail">
						<img alt="" src="<?= Url::to(['en/images/emergency_medicine.jpg']) ?>">
					</div>
					
					<?php
		        		foreach($clinics as $object) {
		        			echo '<div class="blog-content">';
							echo '<h3>'. $object->title_en .'</h3>';
							echo '<p>'. $object->content_en .'</p>';
							echo '</div>';
		        		}
		        	?>
								
				</article>
				
				
			</div>
			
		</div>
		
	</div>



</div><!--end sub-page-content-->

views/en/Contact.php
<?php
use yii\helpers\Url;
?>


<!-- Sub Page Banner
============================================= -->
<section class="sub-page-banner text-center" data-stellar-background-ratio="0.3">
	
	<div class="overlay"></div>
	
	<div class="container">
		<h1 class="entry-title">Contact Us</h1>
		<p>Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets.</p>
	</div>
	
</section>




<!-- Sub Page Content
============================================= -->
<div id="sub-page-content" class="clearfix">
	
	<div class="container">
		
		<h2 class="light bordered">Get<span>Directions</span></h2>
		
		<div class="row">
			
			<div class="col-md-12">
				
				<!-- Map
				============================================= -->
				<script src="https://maps.googleapis.com/maps/api/js?v=3key=AIzaSyASm3CwaK9qtcZEWYa-iQwHaGi3gcosAJc&sensor=false"></script>
				<script src="<?= Url::to(['en/js/map.js']) ?>"></script>
				<div class="map" id="map"></div>
				
			</div>
			
		</div>
		
		<div class="row">
			
			<div class="col-md-8">
				
				<h2 class="light bordered">Give us a <span>Message</span></h2>
				
				
				<!-- Contact Form
				============================================= -->
				<div class="contact-form clearfix">
					<div id="message-contact" class="success" style="display:none;">Thank you! we'll contact you shortly.</div>
					<form name="contact_form" id="contact_form" action="php/submit_contact_form.php" method="POST" onSubmit="return false;">
						<input type="text" name="fname" id="fname" placeholder="First Name" onKeyPress="removeChecks();">
						<input type="text" name="email_address" id="email_address" placeholder="Email Address" onKeyPress="removeChecks();">
						<input type="text" name="subject" id="subject" placeholder="Subject">
						<select name="type" id="type">
							<option value="Note">Note</option>
							<option value="Complaint">Complaint</option>
							<option value="Enquiry">Enquiry</option>
							<option value="Suggestion">Suggestion</option>
						</select>
						<textarea placeholder="Message" name="msg" id="msg"></textarea>
						<input type="submit" class="btn btn-default" value="Submit" onClick="validateContact();">
					</form>
				</div>
				
			</div>
			
			<div class="col-md-4">
				
				<h2 class="light bordered">get in <span>touch</span></h2>
				
				
				<!-- Get in Touch Widget
				============================================= -->
				<div class="get-in-touch-widget">
					
					<ul class="list-unstyled">
						<li><i class="fa fa-phone"></i>016 325 9900</li>
						<li><i class="fa fa-fax"></i>016 325 8226</li>
						<li><i class="fa fa-envelope"></i>P.O. BOX 13286<br>Buraydeh 51493<br>Saudi Arabia</li>
						<li><i class="fa fa-clock-o"></i>Saturday-Thursday: 8:00 am till 2:00 am<br>Friday: 1:00 pm till 1:00 am</li>
						<li><i class="fa fa-globe"></i><a href="http://fcc.med.sa/">fcc.med.sa</a></li>
						<li>
							<div class="rw-ui-container"></div>
						</li>
					</ul>
					
				</div>
				
				
				<!-- Social
				============================================= -->
				<ul class="social-rounded">
					<li><a href="https://www.facebook.com/profile.php?id=100012029535228"><i class="fa fa-facebook"></i></a></li>
					<li><a href="https://twitter.com/fcc_clinis"><i class="fa fa-twitter"></i></a></li>
					<li><a href="https://www.instagram.com/fcc_clinis/"><i class="fa fa-instagram"></i></a></li>
					<li><a href="#."><i class="fa fa-google-plus"></i></a></li>
					<li><a href="#."><i class="fa fa-youtube"></i></a></li>
					<li><a href="#."><i class="fa fa-linkedin"></i></a></li>
				</ul>
				
			</div>
			
		</div>
		
	</div>



</div><!--end sub-page-content-->

views/en/Departments.php
<?php
use yii\helpers\Url;
?>

<!-- Sub Page Content
============================================= -->
<div id="sub-page-content" class="clearfix">

	<div class="container">
		
		<div class="row">
		
			<div class="col-md-12 blog-wrapper clearfix">
				
				<h2 class="bordered light">Departments</h2>
				
				<article class="blog-item blog-full-width blog-detail">
					
					<div class="blog-thumbnail">
						<img alt="" src="<?= Url::to(['en/images/ultrasound.jpg']) ?>">
					</div>
					
					<?php
		        		foreach($departments as $object) {
		        			echo '<div class="blog-content">';
							echo '<h3>'. $object->title_en .'</h3>';
							echo '<p>'. $object->content_en .'</p>';
							echo '</div>';
		        		}
		        	?>
								
				</article>
				
				
			</div>
			
		</div>
		
	</div>



</div><!--end sub-page-content-->

views/en/Gallery.php
<?php
use yii\helpers\Url;
?>

<!-- Sub Page Banner
============================================= -->
<section class="sub-page-banner text-center" data-stellar-background-ratio="0.3" style="background: url(<?= Url::to(['en/images/gallery-banner.jpg']) ?>) no-repeat center" >
	<div class="overlay"></div>
	<div class="container">
		<h1 class="entry-title">Gallery</h1>
	</div>
</section>



<!-- Sub Page Content
============================================= -->
<div id="sub-page-content" class="clearfix">
	
	
	
	<div class="container">
	
	
		<!-- BEGIN GALLERY SECTION -->

		<section class="gallery no-padding">
				
				<div id="Container-gallery">
					
					<ul class="four-column-gallery clearfix">
						
						<!-- Item -->
						<?php
						$images = glob('../gallery/*.{jpg,JPG,jpeg,JPEG,png,PNG}', GLOB_BRACE);
				        foreach($images as $img) {
				            echo '<li class="mix">';
							echo '<div class="gallery-item">';
							echo '<div class="gallery-item-thumb">';
							echo '<span class="overlay"></span>';
							echo '<img height="200px" src="' . Url::to([$img]) . '" alt="Gallery Item">';
							echo '<a href="' . Url::to([$img]) . '" data-fancybox-group="portfolio" class="hover-button-plus fancybox"></a>';
							echo '</div>';
							echo '<div class="gallery-item-info">';
							echo '</div>';
							echo '</div>';
							echo '</li>';
				        }
				        ?>
						<!-- End Item -->
						
					</ul>
					
				</div>

				
		</section><!-- END GALLERY SECTION -->

		
	</div>
		
			  
</div><!--end sub-page-content-->

views/en/Home.php
<?php
use yii\helpers\Url;
?>


<!-- Main Banner
============================================= -->
<section id="slider" class="tp-banner-container index-rev-slider clearfix">
	
	<div class="fullwidthabnner">
	
		<ul>	
		
			<?php
				$images = glob('../banners/*.{jpg,JPG,jpeg,JPEG,png,PNG}', GLOB_BRACE);
				$images = array_reverse($images);
				foreach($images as $img) {
					echo '<li data-transition="slideright">';
					echo '<img src="' . Url::to([$img]) . '"/>';
					echo '</li>';
				}
			?>
		
		</ul>		
		
	</div>	
	
</section>






<!-- Home Boxes
============================================= -->
<div class="row text-center no-margin">

	<div class="col-md-4 bg-default">
		
		<div class="home-box">
			<span class="glyphicon glyphicon-tint"></span>
			<h3>Full Medical Services</h3>
			<p>Request to visit home physical therapy contact via IRC / mobile 0556334446</p>
		</div>
		
	</div>
	
	<div class="col-md-4">
		
		<div class="home-box opening-hours clearfix">
			
			<span class="glyphicon glyphicon-time"></span>
			<h3>Opening Hours</h3>
			<br>
			
			<ul class="list-unstyled">
				<li class="clearfix">
					<span>
						Staurday - Thursday
					</span>
					<div class="value">
						8:00 am till 2:00 am
					</div>
				</li>
				<li class="clearfix">
					<span>
						Friday
					</span>
					<div class="value">
						1:00 pm till 1:00 am
					</div>
				</li>
			</ul>
		
		</div>
		
	</div>
	
	<div class="col-md-4 bg-default">
		
		<div class="home-box">
			<span class="glyphicon glyphicon-tint"></span>
			<h3>Emergency Services</h3>
			<p>Our medical fleet is available 24 hours a day for emergency services.</p>
		</div>
		
	</div>
	
</div>


<!-- Appointment
============================================= -->
<section class="appointment-sec text-center">
	
	<div class="container">
		
		<h1>Make an appointment</h1>
		<p class="lead">Now you can reserve an appointment online without going to the clinics. Make an appointment then wait for confirmation.</p>
		
		<div class="row">
			
			<div class="col-md-6">
				<figure><img src="<?= Url::to(['en/images/appointment-img.jpg']) ?>" alt="image" title="Appointment image" class="img-responsive lady1"></figure>
			</div>
			
			<div class="col-md-6">
				<div class="appointment-form clearfix">
				   <div class="success" id="message-app" style="display:none;"></div>
					<form name="appoint_form" id="appoint_form" method="post" action="submit.php" onSubmit="return false">
						<input type="text" name="app_fname" id="app_fname" placeholder="First Name" onKeyPress="removeChecks();">
						<input type="text" name="app_lname" id="app_lname" placeholder="Last Name" onKeyPress="removeChecks();">
						<input type="email" name="app_email_address" id="app_email_address" placeholder="Email Address" onKeyPress="removeChecks();">
						<input type="text" name="app_phone" id="app_phone" placeholder="Phone No">
						<input type="text" name="datepicker" id="datepicker" placeholder="Appointment Date" onClick="removeChecks();">
						<select name="gender" id="gender">
							<option>Male</option>
							<option>Female</option>
							<option>Child</option>
						</select>
						<textarea placeholder="Message" name="app_msg" id="app_msg"></textarea>
						<input type="submit" value="submit" class="btn btn-default btn-rounded" onClick="validateAppoint();">
					</form>
				</div>
			</div>
			
		</div>
		
	</div>
	
</section>


<!-- Latest News
============================================= -->
<section class="latest-news">

	<div class="container">
	
		<div class="row">
			
			<div class="col-md-6">
				
				<h2 class="bordered light">Latest <span>News</span> <a href="<?= Url::to(['en/all-news']) ?>" class="btn btn-default btn-xs pull-right">All</a></h2>
				
				<div class="row">
					
					<?php
		        		foreach($news as $news_object) {
		        			$timestamp = strtotime($news_object["created_at"]);
		        			$year = date('Y', $timestamp); // 1-7
							$month = date('M', $timestamp); // 1-12
							$day = date('d', $timestamp); // 1-31
		        	?>

		        	<div class="col-md-6">
						<article class="blog-item">
							<div class="blog-thumbnail">
								<div class="blog-date"><p class="day"><?= $day ?></p><p class="monthyear"><?= $month . ' ' . $year ?></p></div>
								<img src='<?= Url::to(["../news/$news_object->image_name"]) ?>' alt="" title="News Image">
							</div>
							<div class="blog-content">
								<h4 class="blog-title" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;"><a href='<?= Url::to(["en/news?id=$news_object->id"]) ?>'><?= $news_object["title_en"] ?></a></h4>
								<p style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;"><?php echo $news_object["content_en"]; ?></p>
							</div>
						</article>	
					</div>

		        	<?php
		        		}
		        	?>
					
				</div>
				
			</div>
			
			
			<!-- Sidebar
			============================================= -->
			<aside class="col-md-6">
				
					<h2 class="bordered light">Health <span>Advise</span> <a href="<?= Url::to(['en/all-articles']) ?>" class="btn btn-default btn-xs pull-right">All</a></h2>
					<p>The Basics to Practice Every Day<br>He who has health has hope, and he who has hope has everything. "Arabian Proverb"</p>
					<div class="panel-group" id="accordion">
					  
						<?php
							$index = 0;
			        		foreach($articles as $article) {
			        	?>

						<div class="panel panel-default">
							<div class="panel-heading">
							  <h4 class="panel-title">
								<a data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $index; ?>">
								  <span><i class="fa fa-plus"></i></span><?php echo $article["title_en"]; ?>
								</a>
							  </h4>
							</div>
							<div id="collapse<?php echo $index; ?>" class="panel-collapse collapse">
							  <div class="panel-body">
							   <?php echo $article["content_en"]; ?>
							  </div>
							</div>
						  </div>

			        	<?php
			        			$index++;
			        		}
			        	?>
					  
					</div>
			
			</aside>
			
		</div>
		
	</div>
	
</section>



<!-- App Store
============================================= -->
<section class="medicom-app" data-stellar-background-ratio="0.3">
	<div class="container">
		<div class="row">
			<div class="col-md-5">
				<img src="<?= Url::to(['en/images/mobile-hand.png']) ?>" class="app-img" alt="" title="">
			</div>
			<div class="col-md-7">
				<div class="medicom-app-content">
					<h1>Future Care Clinics App Available</h1>
					<p class="lead">Now you can download our apps for smartphones
					<span>AVAILABLE ON STORES</span>
					</p>
					<ul class="list-unstyled app-buttons">
						<li><a href="#."><img src="<?= Url::to(['en/images/app-store-btn.png']) ?>" alt="" title="App Store"></a></li>
						<li><a href="#."><img src="<?= Url::to(['en/images/play-store-btn.png']) ?>" alt="" title="Google App"></a></li>
					</ul>
					</div>
			</div>
		</div>
	</div>
</section>




<!-- Testimonials
============================================= -->
<section class="testimonials bg-white text-center">
	
	<div class="container">
		
		<h2>Clients</h2>
		<div class="row">
	
			<div class="col-md-12">
			
				<div id="carousel-testimonials" class="owl-carousel slide testimonials-carousel">

					<!-- Item -->
					<?php
					$images = glob("../clients/*.{jpg,JPG,jpeg,JPEG,png,PNG}", GLOB_BRACE);
			        foreach($images as $img) {
			            echo '<div class="item" style="vertical-alig: middle;">';
						echo '<div class="testimonials-patient-detail">';
						echo '<img src="' . Url::to([$img]) . '" class="img-thumbnail" alt="" title="">';
						echo '</div>';
						echo '</div>';
			        }
			        ?>
					<!-- End Item -->
					
				</div>

			</div>
	
		</div>
	
	</div>
	
</section>

views/en/News.php
<?php
use yii\helpers\Url;
?>

<!-- Sub Page Content
============================================= -->
<div id="sub-page-content" class="clearfix">

	<div class="container">
		
		<div class="row">
		
			<div class="col-md-12 blog-wrapper clearfix">
				
				<h2 class="bordered light"><span><?= $news->title_en ?></span></h2>
				
				<article class="blog-item blog-full-width blog-detail">
					
					<div class="col-md-4">
						<div class="blog-thumbnail">
							<img alt="" src="<?= Url::to(['../news/' . $news->image_name]) ?>">
						</div>
					</div>

					<div class="col-md-8">
	        			<div class="blog-content">
							<p><?= $news->content_en ?></p>
						</div>
					</div>
		        	
				</article>
				
				
			</div>
			
		</div>
		
	</div>



</div><!--end sub-page-content-->