controllers/ArController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

use app\models\Article;
use app\models\News;
use app\models\Clinic;
use app\models\Department;
use app\models\Doctor;
use app\models\Visit;


class ArController extends Controller
{

    public function actionHome()
    {
        $visit = new Visit();
        $visit->save();

        $this->layout = 'ar';

        $news = News::find()->limit(4)->orderBy(['id' => SORT_DESC])->all();
        $articles = Article::find()->limit(10)->orderBy(['id' => SORT_DESC])->all();

        return $this->render('Home', [
            'news' => $news,
            'articles' => $articles,
        ]);
    }


    public function actionClinics()
    {
        $this->layout = 'ar';

        $clinics = Clinic::find()->all();
        return $this->render('Clinics', [
            'clinics' => $clinics
        ]);
    }


    public function actionDepartments()
    {
        $this->layout = 'ar';

        $departments = Department::find()->all();
        return $this->render('Departments', [
            'departments' => $departments
        ]);
    }


    public function actionGallery()
    {
        $this->layout = 'ar';
        return $this->render('Gallery');
    }


    public function actionAbout()
    {
        $this->layout = 'ar';
        $doctors = Doctor::find()->all();
        return $this->render('About', [
            'doctors' => $doctors
        ]);
    }


    public function actionContact()
    {
        $this->layout = 'ar';
        return $this->render('Contact');
    }


    public function actionAllNews()
    {
        $this->layout = 'ar';

        $news = News::find()->orderBy(['id' => SORT_DESC])->all();
        return $this->render('AllNews', [
            'news' => $news,
        ]);
    }


    public function actionNews()
    {
        if (isset($_GET['id']))
        {
            $this->layout = 'ar';

            $news = News::find()->where(["id" => $_GET['id']])->one();
            return $this->render('News', [
                'news' => $news,
            ]);
        }
        
        return $this->redirect(Yii::$app->request->referrer);
    }


    public function actionAllArticles()
    {
        $this->layout = 'ar';

        $articles = Article::find()->orderBy(['id' => SORT_DESC])->all();
        return $this->render('AllArticles', [
            'articles' => $articles,
        ]);
    }
    
}

views/ar/About.php
<?php
use yii\helpers\Url;
?>

<!-- Sub Page Banner
============================================= -->
<section class="sub-page-banner text-center" data-stellar-background-ratio="0.3" style="background: url(<?= Url::to(['ar/images/about-banner.jpg']) ?>) no-repeat center">
	
	<div class="overlay"></div>
	
	<div class="container">
		<h1 class="entry-title">عن العيادات</h1>
		<p></p>
	</div>
	
</section>



<!-- Sub Page Content
============================================= -->
<div id="sub-page-content">


	<div class="container big-font">
	
		<h2 class="light bordered main-title"><span>رسالتنا</span></h2>
    	<p class="footer-bottom-text">نحن نؤمن إيماناً كاملاً وراسخاً بضرورة المضي في رفع مقاييس الجودة للرعاية الطبية وتلبية تطلعات عملائنا من خلال أطباء و طاقم إداري فعّال و ذي جاهزية عالية و تفاني في الأداء و تجهيزات ذات تقنية متطورة.</p>

    	<h2 class="light bordered main-title"><span>مبادئنا</span></h2>
    	<ul>
    		<li>الأمانة الطبية في المقام الأول</li>
			<li>المريض هو محور الاهتمام الأول</li>
			<li>الرقي بالجو العام للعمل .</li>
			<li>التدريب و التعليم أساس الاستمرار .</li>
			<li>جو مريح و صحي للمريض .</li>
			<li>الواحد للكل و الكل للواحد .</li>
			<li>الوقاية الطبية ضد العدوى .</li>
			<li>أن نكون من أفضل المراكز الطبية في المحيط الإقليمي .</li>
    	</ul>
	
		<h2 class="light bordered main-title"><span>رسالتنا</span></h2>
    	<p class="footer-bottom-text">الاستمرار في تقديم الرعاية الطبية معتمدين على أحدث ما توصل إليه الطب و البحث العلمي وتجديد خبراتنا و التطوير المستمر للطاقم الطبي لدينا و العاملين بشكل عام ، وذلك من خلال:<br>
    	<ul>
    		<li>تقديم مستوى عالي من العناية الطبية .</li>
			<li>الرقي بالكوادر الوطنية .</li>
			<li>الاستمرار في البحث عن الجودة النوعية في الرعاية الصحية .</li>
			<li>خصوصية المريض و المهنة العالية .</li>
			<li>المرونة الإدارية.</li>
    	</ul></p>

	</div>


	<div class="height20"></div>


<!-- Team
============================================= -->
<section class="testimonials bg-white text-center">
	
	<div class="container">
		
		<div class="text-center">
			<h1 class="light">تعرف على <span>افضل الاطباء</span></h1>
		</div>
		
		<div class="height50"></div>
		
		<div id="carousel-testimonials" class="owl-carousel slide testimonials-carousel">
			

			<?php
				foreach($doctors as $object) {
					echo '<div class="team-member">';
					echo '<div class="team-thumb">';
					echo '<img src="' . Url::to(['../doctors/'. $object->image_name]) . '" class="img-rounded" alt="">';
					echo '</div>';
					echo '<h5 style="color: #552f7c;">'. $object->name_ar .'</h5>';
					echo '<h5><span>'. $object->job_position_ar .'</span></h5>';
					echo '<p class="text-center">'. $object->working_hours_ar .'</p>';
					echo '<p class="text-center">'. $object->ext_doctor_ar .'</p>';
					echo '</div>';
				}
			?>

			
		 </div>

	</div>
	
	<div class="height50"></div>
	
</section>

views/ar/AllArticles.php
<!-- Articles
============================================= -->
<section class="latest-news">

	<div class="container">
	
		<div class="row">
			
			
			<!-- Sidebar
			============================================= -->
			<aside class="col-md-12">
				
				<h2 class="bordered light">نصائح <span>طبية</span></h2>
				<div class="panel-group" id="accordion">


					<?php
						$index = 0;
		        		foreach($articles as $article) {
		        	?>

					<div class="panel panel-default">
						<div class="panel-heading">
						  <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapse<?= $index ?>">
							  <span><i class="fa fa-plus"></i></span><?= $article->title_ar ?>
							</a>
						  </h4>
						</div>
						<div id="collapse<?= $index ?>" class="panel-collapse collapse">
						  <div class="panel-body">
						   <?= $article->content_ar ?>
						  </div>
						</div>
					  </div>

		        	<?php
		        			$index++;
		        		}
		        	?>

				  
				</div>
			
			</aside>
			
		</div>
		
	</div>
	
</section>

views/ar/AllNews.php
<?php
use yii\helpers\Url;
?>

<!-- Latest News
============================================= -->
<section class="latest-news">

	<div class="container">
	
		<div class="row">
			
			<div class="col-md-12">
				
				<h2 class="bordered light">كل <span>الآخبار</span></h2>
				
				<div class="row">

					<?php
		        		foreach($news as $news_object) {
		        			$timestamp = strtotime($news_object->created_at);
		        			$year = date('Y', $timestamp); // 1-7
							$month = date('M', $timestamp); // 1-12
							$day = date('d', $timestamp); // 1-31
		        	?>

		        	<div class="col-md-6 pull-right">
						<article class="blog-item">
							<div class="blog-thumbnail">
								<div class="blog-date"><p class="day"><?= $day ?></p><p class="monthyear"><?= $month . ' ' . $year ?></p></div>
								<img src="<?= Url::to(['../news/' . $news_object->image_name]) ?>" alt="" title="News Image">
							</div>
							<div class="blog-content">
								<h4 class="blog-title"><a href="<?= Url::to(['ar/news?id=' . $news_object->id]) ?>"><?= $news_object->title_ar ?></a></h4>
								<p><?= $news_object->content_ar ?></p>
							</div>
						</article>	
					</div>

		        	<?php
		        		}
		        	?>
					
					
				</div>
				
			</div>
			
		</div>
		
	</div>
	
</section>

views/ar/Clinics.php
<?php
use yii\helpers\Url;
?>

<!-- Sub Page Content
============================================= -->
<div id="sub-page-content" class="clearfix">

	<div class="container">
		
		<div class="row">
		
			<div class="col-md-12 blog-wrapper clearfix">
				
				<h2 class="bordered light"><span>العيادات</span></h2>
				
				<article class="blog-item blog-full-width blog-detail">
					
					<div class="blog-thumbnail">
						<img alt="" src="<?= Url::to(['ar/images/emergency_medicine.jpg']) ?>">
					</div>

					<?php
		        		foreach($clinics as $object) {
		        			echo '<div class="blog-content">';
							echo '<h3 style="direction: rtl;">'. $object->title_ar .'</h3>';
							echo '<p>'. $object->content_ar .'</p>';
							echo '</div>';
		        		}
		        	?>
								
				</article>
				
				
			</div>
			
		</div>
		
	</div>



</div><!--end sub-page-content-->

views/ar/Contact.php
<?php
use yii\helpers\Url;
?>

<!-- Sub Page Banner
============================================= -->
<section class="sub-page-banner text-center" data-stellar-background-ratio="0.3">
	
	<div class="overlay"></div>
	
	<div class="container">
		<h1 class="entry-title">اتصل بنا</h1>
		<p>ورغبة من إدارة عيادات عناية المستقبل في تقديم أفضل الخدمات التي تليق بك والسعي الحثيث إلى التطوير للأفضل فإننا نأمل إبلاغنا إذا شعرتم بتأخر خدمتكم أو كان لديكم ملاحظه حول الإجراءات المطبقة أو تقصير في التـعامل معكم فـإن إدارة العيادات تأمل منكم إبلاغها عن طريق تعبئة هذا النموذج متمنين لكم دوام الصحة و التوفيق . . .</p>
	</div>
	
</section>




<!-- Sub Page Content
============================================= -->
<div id="sub-page-content" class="clearfix">
	
	<div class="container">
		
		<h2 class="light bordered">موقعنا علي <span>الخريطة</span></h2>
		
		<div class="row">
			
			<div class="col-md-12">
				
				<!-- Map
				============================================= -->
				<script src="https://maps.googleapis.com/maps/api/js?v=3key=AIzaSyASm3CwaK9qtcZEWYa-iQwHaGi3gcosAJc&sensor=false"></script>
				<script src="<?= Url::to(['ar/js/map.js']) ?>"></script>
				<div class="map" id="map"></div>
				
			</div>
			
		</div>
		
		<div class="row">
			
			<div class="col-md-4">
				
				<h2 class="light bordered">get in <span>touch</span></h2>
				
				
				<!-- Get in Touch Widget
				============================================= -->
				<div class="get-in-touch-widget">
					
					<ul class="list-unstyled">
						<li><i class="fa fa-phone"></i>016 325 9900</li>
						<li><i class="fa fa-fax"></i>016 325 8226</li>
						<li><i class="fa fa-envelope"></i>صندوق بريد رقم 13286<br>بريدة 51493<br>بالمملكة العربية السعودية</li>
						<li><i class="fa fa-clock-o"></i>السبت-الخميس: 8:00 ص حتي 2:00 ص<br>الجمعه: 1:00 م حتي 1:00 ص</li>
						<li><i class="fa fa-globe"></i><a href="http://fcc.med.sa/">fcc.med.sa</a></li>
						<li>
							<div class="rw-ui-container"></div>
						</li>
					</ul>
					
				</div>
				
				
				<!-- Social
				============================================= -->
				<ul class="social-rounded">
					<li><a href="https://www.facebook.com/profile.php?id=100012029535228"><i class="fa fa-facebook"></i></a></li>
					<li><a href="https://twitter.com/fcc_clinis"><i class="fa fa-twitter"></i></a></li>
					<li><a href="https://www.instagram.com/fcc_clinis/"><i class="fa fa-instagram"></i></a></li>
					<li><a href="#."><i class="fa fa-google-plus"></i></a></li>
					<li><a href="#."><i class="fa fa-youtube"></i></a></li>
					<li><a href="#."><i class="fa fa-linkedin"></i></a></li>
				</ul>
				
			</div>

			<div class="col-md-8">
				
				<h2 class="light bordered">ارسل <span>رسالتك</span></h2>
				
				
				<!-- Contact Form
				============================================= -->
				<div class="contact-form clearfix">
					<div id="message-contact" class="success" style="display:none;">شكرا لك. سنحاول التواصل معك في أقرب وقت</div>
					<form name="contact_form" id="contact_form" action="php/submit_contact_form.php" method="POST" onSubmit="return false;">
						<input type="text" name="fname" id="fname" placeholder="الاسم الأول" onKeyPress="removeChecks();">
						<input type="text" name="email_address" id="email_address" placeholder="البريد الالكتروني" onKeyPress="removeChecks();">
						<input type="text" name="subject" id="subject" placeholder="العنوان">
						<select name="type" id="type">
							<option value="ملاحظة">ملاحظة</option>
							<option value="شكوي">شكوي</option>
							<option value="استفسار">استفسار</option>
							<option value="مقترح">مقترح</option>
						</select>
						<textarea placeholder="محتوي الرسالة" name="msg" id="msg"></textarea>
						<input type="submit" class="btn btn-default pull-left" value="ارسال" onClick="validateContact();">
					</form>
				</div>
				
			</div>
			
		</div>
		
	</div>



</div><!--end sub-page-content-->

views/ar/Departments.php
<?php
use yii\helpers\Url;
?>

<!-- Sub Page Content
============================================= -->
<div id="sub-page-content" class="clearfix">

	<div class="container">
		
		<div class="row">
		
			<div class="col-md-12 blog-wrapper clearfix">
				
				<h2 class="bordered light"><span>الأقسام</span></h2>
				
				<article class="blog-item blog-full-width blog-detail">
					
					<div class="blog-thumbnail">
						<img alt="" src="<?= Url::to(['ar/images/ultrasound.jpg']) ?>">
					</div>

					<?php
		        		foreach($departments as $object) {
		        			echo '<div class="blog-content">';
							echo '<h3 style="direction: rtl;">'. $object->title_ar .'</h3>';
							echo '<p>'. $object->content_ar .'</p>';
							echo '</div>';
		        		}
		        	?>
		        	
				</article>
				
				
			</div>
			
		</div>
		
	</div>



</div><!--end sub-page-content-->

views/ar/Gallery.php
<?php
use yii\helpers\Url;
?>

<!-- Sub Page Banner
============================================= -->
<section class="sub-page-banner text-center" data-stellar-background-ratio="0.3" style="background: url(<?= Url::to(['en/images/gallery-banner.jpg']) ?>) no-repeat center" >
	<div class="overlay"></div>
	<div class="container">
		<h1 class="entry-title">الاستوديو</h1>
	</div>
</section>



<!-- Sub Page Content
============================================= -->
<div id="sub-page-content" class="clearfix">
	
	
	
	<div class="container">
	
	
		<!-- BEGIN GALLERY SECTION -->

		<section class="gallery no-padding">
				
				<div id="Container-gallery">
					
					<ul class="four-column-gallery clearfix">
						
						<!-- Item -->
						<?php
						$images = glob('../gallery/*.{jpg,JPG,jpeg,JPEG,png,PNG}', GLOB_BRACE);
				        foreach($images as $img) {
				            echo '<li class="mix">';
							echo '<div class="gallery-item">';
							echo '<div class="gallery-item-thumb">';
							echo '<span class="overlay"></span>';
							echo '<img height="200px" src="' . Url::to([$img]) . '" alt="Gallery Item">';
							echo '<a href="' . Url::to([$img]) . '" data-fancybox-group="portfolio" class="hover-button-plus fancybox"></a>';
							echo '</div>';
							echo '<div class="gallery-item-info">';
							echo '</div>';
							echo '</div>';
							echo '</li>';
				        }
				        ?>
						<!-- End Item -->
						
					</ul>
					
				</div>

				
		</section><!-- END GALLERY SECTION -->

		
	</div>
		
			  
</div><!--end sub-page-content-->

views/ar/Home.php
<?php
use yii\helpers\Url;
?>

<!-- Main Banner
============================================= -->
<section id="slider" class="tp-banner-container index-rev-slider clearfix">
	
	<div class="fullwidthabnner">
	
		<ul>	
		
			<?php
				$images = glob('../banners/*.{jpg,JPG,jpeg,JPEG,png,PNG}', GLOB_BRACE);
				$images = array_reverse($images);
				foreach($images as $img) {
					echo '<li data-transition="slideright">';
					echo '<img width="100%" height="auto" src="' . Url::to([$img]) . '"/>';
					echo '</li>';
				}
			?>
		
		</ul>
	</div>
	
</section>






<!-- Home Boxes
============================================= -->
<div class="row text-center no-margin">

	<div class="col-md-4 bg-default">
		
		<div class="home-box">
			<span class="glyphicon glyphicon-tint"></span>
			<h3>خدمات طبية متكامله</h3>
			<p>لطلب زيارة العلاج الطبيعي المنزلي الاتصال عبر جوال المركز / 0556334446</p>
		</div>
		
	</div>
	
	<div class="col-md-4">
		
		<div class="home-box opening-hours clearfix">
			
			<span class="glyphicon glyphicon-time"></span>
			<h3>ساعات العمل</h3>
			
			<ul class="list-unstyled">
				<li class="clearfix">
					<span>
						السبت - الخميس
					</span>
					<div class="value">
						8:00 ص حتي 2:00 ص
					</div>
				</li>
				<li class="clearfix">
					<span>
						الجمعه
					</span>
					<div class="value">
						1:00 م حتي 1:00 ص
					</div>
				</li>
			</ul>
		
		</div>
		
	</div>

	<div class="col-md-4 bg-default">
		
		<div class="home-box">
			<span class="glyphicon glyphicon-tint"></span>
			<h3>العيادات المنزلية</h3>
			<p>أسطول طبي متكامل لتلبية احتياجاتكم داخل وخارج المنطقة</p>
		</div>
		
	</div>
	
</div>


<!-- Appointment
============================================= -->
<section class="appointment-sec text-center">
	
	<div class="container">
		
		<h1>احجز موعد</h1>
		<p class="lead">الآن يمكنك حجز ميعادك اونلاين دون الحاجة للذهاب للمركز. فقط سجل بياناتك وانتظر تأكيد الحجز</p>
		
		<div class="row">
			
			<div class="col-md-6 pull-right">
				<figure><img src="<?= Url::to(['ar/images/appointment-img.jpg']) ?>" alt="image" title="Appointment image" class="img-responsive lady1"></figure>
			</div>
			
			<div class="col-md-6">
				<div class="appointment-form clearfix">
				   <div class="success" id="message-app" style="display:none;"></div>
					<form name="appoint_form" id="appoint_form" method="post" action="submit.php" onSubmit="return false">
						<input type="text" name="app_fname" id="app_fname" placeholder="الاسم الاول" onKeyPress="removeChecks();">
						<input type="text" name="app_lname" id="app_lname" placeholder="اسم العائلة" onKeyPress="removeChecks();">
						<input type="email" name="app_email_address" id="app_email_address" placeholder="البريد الالكتروني" onKeyPress="removeChecks();">
						<input type="text" name="app_phone" id="app_phone" placeholder="رقم الجوال">
						<input type="text" name="datepicker" id="datepicker" placeholder="تاريخ الحجز" onClick="removeChecks();">
						<select name="gender" id="gender">
							<option>ذكر</option>
							<option>انثي</option>
							<option>طفل</option>
						</select>
						<textarea placeholder="محتوي الرسالة" name="app_msg" id="app_msg"></textarea>
						<input type="submit" value="احجز" class="btn btn-default btn-rounded" onClick="validateAppoint();">
					</form>
				</div>
			</div>
			
		</div>
		
	</div>
	
</section>


<!-- Latest News
============================================= -->
<section class="latest-news">

	<div class="container">
	
		<div class="row">
			
			<div class="col-md-6 pull-right">
				
				<h2 class="bordered light">أحدث <span>الآخبار</span> <a href="<?= Url::to(['ar/all-news']) ?>" class="btn btn-default btn-xs pull-left">الكل</a></h2>
				
				<div class="row">

					<?php
		        		foreach($news as $news_object) {
		        			$timestamp = strtotime($news_object->created_at);
		        			$year = date('Y', $timestamp); // 1-7
							$month = date('M', $timestamp); // 1-12
							$day = date('d', $timestamp); // 1-31
		        	?>

		        	<div class="col-md-6 pull-right">
						<article class="blog-item">
							<div class="blog-thumbnail">
								<div class="blog-date"><p class="day"><?= $day ?></p><p class="monthyear"><?= $month . ' ' . $year ?></p></div>
								<img src='<?= Url::to(["../news/$news_object->image_name"]) ?>' alt="" title="News Image">
							</div>
							<div class="blog-content">
								<h4 class="blog-title" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;"><a href='<?= Url::to(["ar/news?id=$news_object->id"]) ?>'><?= $news_object->title_ar ?></a></h4>
								<p style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;"><?= $news_object->content_ar ?></p>
							</div>
						</article>	
					</div>

		        	<?php
		        		}
		        	?>
					
					
				</div>
				
			</div>
			
			
			<!-- Sidebar
			============================================= -->
			<aside class="col-md-6">
				
				<h2 class="bordered light">نصائح <span>طبية</span> <a href="<?= Url::to(['ar/all-articles']) ?>" class="btn btn-default btn-xs pull-left">الكل</a></h2>
				<div class="panel-group" id="accordion">


					<?php
						$index = 0;
		        		foreach($articles as $article) {
		        	?>

					<div class="panel panel-default">
						<div class="panel-heading">
						  <h4 class="panel-title">
							<a data-toggle="collapse" data-parent="#accordion" href="#collapse<?= $index ?>">
							  <span><i class="fa fa-plus"></i></span><?= $article->title_ar ?>
							</a>
						  </h4>
						</div>
						<div id="collapse<?= $index ?>" class="panel-collapse collapse">
						  <div class="panel-body">
						   <?= $article->content_ar ?>
						  </div>
						</div>
					  </div>

		        	<?php
		        			$index++;
		        		}
		        	?>

				  
				</div>
			
			</aside>
			
		</div>
		
	</div>
	
</section>



<!-- App Store
============================================= -->
<section class="medicom-app" data-stellar-background-ratio="0.3">
	<div class="container">
		<div class="row">
			<div class="col-md-5 pull-right">
				<img src="<?= Url::to(['ar/images/mobile-hand.png']) ?>" class="app-img" alt="" title="">
			</div>
			<div class="col-md-7">
				<div class="medicom-app-content">
					<h1>تطبيق عيادات عناية المستقبل متاح الآن</h1>
					<p class="lead"><br>الآن يمكنك تحميل تطبيقنا للهواتف الذكية
					<span>متاح علي المتجر</span>
					</p>
					<ul class="list-unstyled app-buttons">
						<li><a href="#."><img src="<?= Url::to(['ar/images/app-store-btn.png']) ?>" alt="" title="App Store"></a></li>
						<li><a href="#."><img src="<?= Url::to(['ar/images/play-store-btn.png']) ?>" alt="" title="Google App"></a></li>
					</ul>
					</div>
			</div>
		</div>
	</div>
</section>




<!-- Testimonials
============================================= -->
<section class="testimonials bg-white text-center">
	
	<div class="container">
		
		<h2>عملائنا</h2>
		<div class="row">
	
			<div class="col-md-12">
			
				<div id="carousel-testimonials" class="owl-carousel slide testimonials-carousel">

					<!-- Item -->
					<?php
					$images = glob("../clients/*.{jpg,JPG,jpeg,JPEG,png,PNG}", GLOB_BRACE);
			        foreach($images as $img) {
			            echo '<div class="item" style="vertical-alig: middle;">';
						echo '<div class="testimonials-patient-detail">';
						echo '<img src="' . Url::to([$img]) . '" class="img-thumbnail" alt="" title="">';
						echo '</div>';
						echo '</div>';
			        }
			        ?>
					<!-- End Item -->
					
				</div>

			</div>
	
		</div>
	
	</div>
	
</section>

views/ar/News.php
<?php
use yii\helpers\Url;
?>

<!-- Sub Page Content
============================================= -->
<div id="sub-page-content" class="clearfix">

	<div class="container">
		
		<div class="row">
		
			<div class="col-md-12 blog-wrapper clearfix">
				
				<h2 class="bordered light"><span><?= $news->title_ar ?></span></h2>
				
				<article class="blog-item blog-full-width blog-detail">
					
					<div class="col-md-4 pull-right">
						<div class="blog-thumbnail">
							<img alt="" src="<?= Url::to(['../news/' . $news->image_name]) ?>">
						</div>
					</div>

					<div class="col-md-8">
	        			<div class="blog-content">
							<p><?= $news->content_ar ?></p>
						</div>
					</div>
		        	
				</article>
				
				
			</div>
			
		</div>
		
	</div>



</div><!--end sub-page-content-->